"""adicionar campo tema_escuro em User

Revision ID: 4d4e0b2c9889
Revises: 64e04dcd8369
Create Date: 2025-08-25 08:23:13.275420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4e0b2c9889'
down_revision = '64e04dcd8369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tema_escuro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notificacoes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('notificacoes')
        batch_op.drop_column('tema_escuro')

    # ### end Alembic commands ###
