"""Adiciona campo ativo ao usuario

Revision ID: 612d60c5f20c
Revises: 4d4e0b2c9889
Create Date: 2025-09-19 15:14:42.883832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612d60c5f20c'
down_revision = '4d4e0b2c9889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cargo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_inativacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('data_inativacao')
        batch_op.drop_column('cargo')
        batch_op.drop_column('endereco')
        batch_op.drop_column('telefone')
        batch_op.drop_column('ultimo_login')
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
