"""adicionar campo role ao usuario

Revision ID: 64e04dcd8369
Revises: ac3c947e1698
Create Date: 2025-08-24 00:05:09.780822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e04dcd8369'
down_revision = 'ac3c947e1698'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('usuario',
        sa.Column('role', sa.String(length=20), nullable=False, server_default='usuario_padrao')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
