"""Adiciona campo data_cadastro ao usuario

Revision ID: ac3c947e1698
Revises: 
Create Date: 2025-08-22 19:19:27.023570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3c947e1698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_movimentacao', schema=None) as batch_op:
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('historico_movimentacao', schema=None) as batch_op:
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
